GET http://localhost:3000/subscribers

### Get Data By ID
GET http://localhost:3000/subscribers/62459fea3f8c4f527419f82b

### Test Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "fullname": "Suphachock2",
    "username": "chokun10101",
    "telephone": "0999999999",
    "email": "chok1@gmail.com",
    "password": "123456"

}

### Test Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    
    "username": "chokun1010",
    "password": "123456"

}

### Update Data
PATCH http://localhost:3000/subscribers/623aa78235202d1b6eb2518c
Content-Type: application/json

{
    "name": "CHOKZZZZ"
}
### Deleted Data
DELETE http://localhost:3000/subscribers/623aa68135202d1b6eb25178