### Test Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "fullname": "sc6",
    "telephone": "1111111111",
    "email": "sc1@gmail.com",
    "password": "sc6"

}

### Test Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    
    "email": "sc1@gmail.com",
    "password": "s1"

}

### Update Data
PATCH http://localhost:3000/subscribers/623aa78235202d1b6eb2518c
Content-Type: application/json

{
    "name": "CHOKZZZZ"
}
### Deleted Data
DELETE http://localhost:3000/subscribers/623aa68135202d1b6eb25178